kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "librechat.fullname" $ }}-configenv
data:
  {{- if (index .Values "librechat-rag-api" "enabled") }}
  RAG_API_URL: http://{{ include "rag.fullname" (index .Subcharts "librechat-rag-api") | lower }}.{{ .Release.Namespace | lower }}.svc.cluster.local:8000 
  {{- end }}
  {{- if .Values.librechat.configEnv }}
  {{- toYaml .Values.librechat.configEnv | nindent 2 }}
  {{- end }}
  {{- if not (dig "configEnv" "MEILI_HOST" "" .Values.librechat) }}
  MEILI_HOST: http://{{ include "meilisearch.fullname" .Subcharts.meilisearch }}.{{ .Release.Namespace | lower }}.svc.cluster.local:7700
  {{- end }}
  {{- if not (dig "configEnv" "MONGO_URI" "" .Values.librechat) | default "" }}
  MONGO_URI: mongodb://user:librechat@librechat-mongo-svc:27017/admin
  {{- end }}