apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express:latest
        env:
        - name: ME_CONFIG_MONGODB_SERVER
          value: "librechat-mongo-svc"  # Use the correct service name
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          value: "user"  # Ensure this matches your MongoDB user
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          value: "librechat"  # Ensure this matches your MongoDB password
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express
spec:
  selector:
    app: mongo-express
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
  type: ClusterIP
